name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js 24
      uses: actions/setup-node@v3
      with:
        node-version: 24

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: olivergw/wordpress-redis:latest
